<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MessageWorker.Application\MessageWorker.Application.csproj" />
    <ProjectReference Include="..\MessageWorker.Domain\MessageWorker.Domain.csproj" />
  </ItemGroup>

</Project>
